### ISSUE TITLE
No LICENSE

### ISSUE THREAD

**Issue by SoniEx2** [josecastillo/r-ainbow-flags#3]
Currently this is licensed as All Rights Reserved (no license = all rights reserved). Please add a license. (WTFPL maybe?)

**Comment by josecastillo** [comment]
Public domain might even work; it would relieve people of the need to credit or display a license. Out of town at the moment but I'll look into it next week.

**Comment by josecastillo** [comment]
I have contacted all of the people who have contributed to this project, and they have all agreed to offer their contributions to the public domain. As such I have added a public domain declaration to the repository.
